"""Initial migration

Revision ID: f031b8753027
Revises:
Create Date: 2022-11-12 14:28:46.015120

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSchema, DropSchema

from alembic import op

# revision identifiers, used by Alembic.
revision = "f031b8753027"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(CreateSchema("transactions"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_status",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "transaction_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__transaction_status__id")),
        schema="transactions",
    )
    op.create_index(
        "ix__transaction_id",
        "transaction_status",
        ["transaction_id"],
        unique=False,
        schema="transactions",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=18, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user__id")),
        sa.UniqueConstraint("name", name=op.f("uq__user__name")),
        schema="transactions",
    )
    op.create_table(
        "user_transaction",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_src_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_dest_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_transaction__id")),
        schema="transactions",
    )
    op.create_index(
        "ix__user_src_id",
        "user_transaction",
        ["user_src_id"],
        unique=False,
        schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix__user_src_id",
        table_name="user_transaction",
        schema="transactions",
    )
    op.drop_table(
        "user_transaction",
        schema="transactions",
    )
    op.drop_table(
        "user",
        schema="transactions",
    )
    op.drop_index(
        "ix__transaction_id",
        table_name="transaction_status",
        schema="transactions",
    )
    op.drop_table(
        "transaction_status",
        schema="transactions",
    )
    # ### end Alembic commands ###

    op.execute(DropSchema("transactions"))
